# Generated by Django 5.0.4 on 2024-04-18 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'HelpDesk сотрудник',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Преподаватели и Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='HelpDeskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorium_number', models.CharField(max_length=100, verbose_name='Аудитория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('conversation', models.JSONField(blank=True, null=True, verbose_name='Диалог')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('decline_reason', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROCESS', 'В обработке'), ('CLOSED', 'Закрыта')], default='NEW', max_length=20, verbose_name='Статус')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to='base.helpdeskuser', verbose_name='Заявку принял')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to='base.lecturer', verbose_name='От')),
            ],
            options={
                'verbose_name_plural': 'Заявки HelpDesk',
            },
        ),
    ]
