# Generated by Django 5.0.4 on 2024-04-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_lecturer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdeskrequest',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='helpdeskrequest',
            name='is_closed',
        ),
    ]
