# Generated by Django 5.0.4 on 2024-04-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_helpdeskrequest_closed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdeskrequest',
            name='decline_reason',
        ),
    ]
